cd miranda-client
echo Installing Angular CLI...
npm install -g @angular/cli
echo Done. Installing devkit...
npm install -g @angular/cli
echo Done. Cleaning up...
npm link
echo Done. Updating...
npm install npm@latest -g
echo Done.